/*******************************************************************************
 * Copyright (c) 2013 -- WPI Suite
 * 
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 ******************************************************************************/
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

import java.awt.Color;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.LayoutStyle.ComponentPlacement;
import javax.swing.SwingConstants;

import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameModel;
import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameRequirementModel;
import edu.wpi.cs.wpisuitetng.modules.planningpoker.view.ImageLoader;

/**
 * Panel to show requirement description for new games
 * @author Team 9
 * @version 1.0
 */
public class RequirementDescriptionOnlyPanel extends javax.swing.JPanel {
    
    private static final long serialVersionUID = 6053116033835102214L;
    
    
    /**
     * Creates new form RequirementDescriptionOnlyPanel
     */
    public RequirementDescriptionOnlyPanel() {
        setBackground(Color.WHITE);
        initComponents();
        
    }
    
    /**
     * Sets the requirement for voting
     * 
     * @param parentGame
     *        the game being displayed
     * @param req
     *        the requirement being shown
     */
    public void setRequirement(GameModel parentGame, GameRequirementModel req) {
        
        reqDescriptionTextArea.setText(req.getDescription());
        setRequirementName(req.getName());
        setRequirementType(req.getType());
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        JLabel lblRequirement = new JLabel("Requirement:");
        
        JScrollPane scrollPane = new JScrollPane();
        
        requirementNameLabel = new JLabel("<requirement>");
        
        JLabel lblDescription = new JLabel("Description:");
        
        JLabel lblType = new JLabel("Type:");
        
        requirementType = new JLabel("<type>");
        
        JPanel ClickStartPanel = new JPanel();
        ClickStartPanel.setBackground(Color.WHITE);
        
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(layout
                .createParallelGroup(Alignment.TRAILING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.TRAILING)
                                                .addComponent(
                                                        scrollPane,
                                                        Alignment.LEADING,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        430, Short.MAX_VALUE)
                                                .addComponent(
                                                        ClickStartPanel,
                                                        Alignment.LEADING,
                                                        GroupLayout.DEFAULT_SIZE,
                                                        430, Short.MAX_VALUE)
                                                .addGroup(
                                                        Alignment.LEADING,
                                                        layout.createSequentialGroup()
                                                                .addComponent(
                                                                        lblRequirement)
                                                                .addGroup(
                                                                        layout.createParallelGroup(
                                                                                Alignment.LEADING)
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addPreferredGap(
                                                                                                        ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        requirementNameLabel))
                                                                                .addGroup(
                                                                                        layout.createSequentialGroup()
                                                                                                .addGap(249)
                                                                                                .addComponent(
                                                                                                        lblType)
                                                                                                .addPreferredGap(
                                                                                                        ComponentPlacement.RELATED)
                                                                                                .addComponent(
                                                                                                        requirementType))))
                                                .addComponent(lblDescription,
                                                        Alignment.LEADING))
                                .addContainerGap()));
        layout.setVerticalGroup(layout.createParallelGroup(Alignment.LEADING)
                .addGroup(
                        layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        layout.createParallelGroup(
                                                Alignment.BASELINE)
                                                .addComponent(lblRequirement)
                                                .addComponent(
                                                        requirementNameLabel)
                                                .addComponent(lblType)
                                                .addComponent(requirementType))
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(lblDescription)
                                .addPreferredGap(ComponentPlacement.RELATED)
                                .addComponent(scrollPane,
                                        GroupLayout.DEFAULT_SIZE, 119,
                                        Short.MAX_VALUE)
                                .addPreferredGap(ComponentPlacement.UNRELATED)
                                .addComponent(ClickStartPanel,
                                        GroupLayout.PREFERRED_SIZE, 114,
                                        GroupLayout.PREFERRED_SIZE)
                                .addContainerGap()));
        
        JLabel lblPressStartGame = new JLabel(
                "Press Start Game to Begin Estimation");
        lblPressStartGame.setHorizontalAlignment(SwingConstants.CENTER);
        lblPressStartGame.setVerticalAlignment(SwingConstants.CENTER);
        lblPressStartGame.setIcon(ImageLoader.getIcon("upArrow.png"));
        ClickStartPanel.add(lblPressStartGame);
        
        reqDescriptionTextArea = new JTextArea();
        reqDescriptionTextArea.setEditable(false);
        reqDescriptionTextArea.setLineWrap(true);
        scrollPane.setViewportView(reqDescriptionTextArea);
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    /**
     * Sets the requirement name
     * 
     * @param text the name of the requirement  
     */
    protected void setRequirementName(String text) {
        requirementNameLabel.setText(text);
    }
    
    /**
     * Sets the requirement type
     * 
     * @param text the name of the type of the requirement 
     */
    protected void setRequirementType(String text) {
        requirementType.setText(text);
    }
    
    private JTextArea reqDescriptionTextArea;
    private JLabel requirementNameLabel;
    private JLabel requirementType;
}
