/**
 * *****************************************************************************
 * Copyright (c) 2013 -- WPI Suite
 * <p>
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 * <p>
 *****************************************************************************
 */
package edu.wpi.cs.wpisuitetng.modules.planningpoker.view.main;

import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.GroupLayout;
import javax.swing.GroupLayout.Alignment;
import javax.swing.JLabel;
import javax.swing.JProgressBar;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextPane;
import javax.swing.LayoutStyle.ComponentPlacement;

import edu.wpi.cs.wpisuitetng.modules.planningpoker.model.GameModel;

/**
 * The requirements panel of the planning poker GUI
 * <p>
 * 
 * @author llhunker, dbtrue
 */
public class UncompletedGameDescriptionPanel extends javax.swing.JPanel {
    
    private final static SimpleDateFormat date_format = new SimpleDateFormat(
            "MM/dd/yyyy hh:mm a");
    
    /**
     *
     */
    private static final long serialVersionUID = 7579915917240962935L;
    
    /**
     * Creates new form NewJPanel
     */
    public UncompletedGameDescriptionPanel() {
        initComponents();
    }
    
    public void setGame(GameModel game) {
        setGameName(game.getName());
        setDescriptionText(game.getDescription());
        setEndDate(game.getEndTime());
        // DefaultListModel<String> listModel = new DefaultListModel<>();
        // listModel.addElement(element);
        // getParticipantsList().setModel(listModel);
    }
    
    protected void setEndDate(Date date) {
        if (date == null) {
            setNoDeadline(true);
        } else {
            setNoDeadline(false);
            setGameDeadlineText(date_format.format(date));
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed"
    // <editor-fold defaultstate="collapsed"
    // desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        nameLabel = new javax.swing.JLabel();
        nameLabel.setText("Name:");
        
        gameName = new JLabel("");
        
        final JLabel lblProgress = new JLabel("Progress:");
        
        progressBar = new JProgressBar();
        
        progressLabel = new JLabel("0/0");
        
        final JScrollPane scrollPane_1 = new JScrollPane();
        
        lblDeadline = new JLabel("Deadline:");
        
        gameDeadline = new JLabel("");
        
        final JTextArea textArea = new JTextArea();
        textArea.setEditable(false);
        
        lblAdmin = new JLabel("Admin:");
        
        lblDeck = new JLabel("Deck:");
        
        deckName = new JLabel("");
        
        final javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        layout.setHorizontalGroup(
            layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nameLabel)
                            .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(gameName))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(154)
                                    .addComponent(lblDeadline)
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(gameDeadline))))
                        .addComponent(scrollPane_1, GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDeck)
                            .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(deckName)
                                    .addPreferredGap(ComponentPlacement.RELATED, 147, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addPreferredGap(ComponentPlacement.RELATED)
                                    .addComponent(lblProgress)
                                    .addPreferredGap(ComponentPlacement.RELATED)))
                            .addComponent(progressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED)
                            .addComponent(progressLabel)))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(Alignment.LEADING)
                        .addComponent(lblAdmin)
                        .addComponent(textArea, GroupLayout.PREFERRED_SIZE, 136, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                        .addComponent(nameLabel)
                        .addComponent(gameName)
                        .addComponent(lblDeadline, GroupLayout.PREFERRED_SIZE, 14, GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblAdmin)
                        .addComponent(gameDeadline))
                    .addPreferredGap(ComponentPlacement.RELATED)
                    .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(scrollPane_1, GroupLayout.PREFERRED_SIZE, 32, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                .addComponent(progressLabel)
                                .addGroup(layout.createParallelGroup(Alignment.BASELINE)
                                    .addComponent(lblDeck)
                                    .addComponent(deckName)
                                    .addComponent(lblProgress))
                                .addComponent(progressBar, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)))
                        .addComponent(textArea, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(186, Short.MAX_VALUE))
        );
        
        descriptionText = new JTextPane();
        descriptionText.setEditable(false);
        scrollPane_1.setViewportView(descriptionText);
        setLayout(layout);
    }// </editor-fold>//GEN-END:initComponents
    
    private javax.swing.JLabel nameLabel;
    private JLabel gameName;
    private JTextPane descriptionText;
    private JProgressBar progressBar;
    private JLabel progressLabel;
    private JLabel gameDeadline;
    private JLabel lblDeadline;
    private JLabel lblAdmin;
    private JLabel lblDeck;
    private JLabel deckName;
    
    protected String getGameName() {
        return gameName.getText();
    }
    
    protected void setGameName(String text) {
        gameName.setText(text);
    }
    
    protected String getDescriptionText() {
        return descriptionText.getText();
    }
    
    protected void setDescriptionText(String text_1) {
        descriptionText.setText(text_1);
    }
    
    protected int getProgressBarValue() {
        return progressBar.getValue();
    }
    
    protected void setProgressBarValue(int value) {
        progressBar.setValue(value);
    }
    
    protected String getProgressLabelText() {
        return progressLabel.getText();
    }
    
    protected void setProgressLabelText(String text_2) {
        progressLabel.setText(text_2);
    }
    
    protected String getGameDeadlineText() {
        return gameDeadline.getText();
    }
    
    protected void setGameDeadlineText(String text_3) {
        gameDeadline.setText(text_3);
    }
    
    /**
     * sets deadline field visible/invisible depending on if game has a deadline
     * 
     * @param status
     *            true if no deadline, false if there is a deadline
     */
    protected void setNoDeadline(boolean status) {
        if (status) {
            lblDeadline.setVisible(false);
            gameDeadline.setVisible(false);
        } else {
            lblDeadline.setVisible(true);
            gameDeadline.setVisible(true);
        }
    }
    protected String getDeckName() {
        return deckName.getText();
    }
    protected void setDeckName(String text_4) {
        deckName.setText(text_4);
    }
}